name: automatic-save-robot
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  bots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run
        run: |
          node -v
          node main.js
          ls -la pic/ | tail -5

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "feat: save robot"
          add: "pic/*"
